version: '3.8'

services:
  ubuntu:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ubuntu_siege_container
    tty: true
    stdin_open: true
    volumes:
      - .:/app
    working_dir: /app
    command: /bin/bash
    ports:
      - "8081:8080" # ホストの8080ポートをコンテナの8080ポートにマッピング
