# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    docker-compose.yml                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: rmatsuba <rmatsuba@student.42tokyo.jp>     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/12/09 17:15:36 by rmatsuba          #+#    #+#              #
#    Updated: 2024/12/09 18:04:01 by rmatsuba         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# version of docker-compose
# version: '3.8'

# services
services:
  cpp-env:
    # build the image from the Dockerfile in the current directory
    build:
      # context: the path to the directory containing the Dockerfile
      context: ..
      # in this case, ../ is root path of this project
      dockerfile: docker/Dockerfile
      # this path is relative to the context 
    # volumes: mount the host directory to the container directory
    volumes:
      # - host directory:container directory
      - ..:/usr/src/app
    # working directory
    working_dir: /usr/src/app
    # tty mode
    # this enable the container to accept interactive commands of bash
    tty: true
