services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "81:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./site:/usr/share/nginx/html
    depends_on:
      - php-fpm

  php-fpm:
    image: php:8.0-fpm
    container_name: php-fpm
    volumes:
      - ./site:/var/www/html
