name: Clang Format Check

on:
  pull_request:
    branches:
      - main

jobs:
  clang-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up clang-format
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format

      - name: Check code formatting
        run: |
          git fetch origin main
          git diff --name-only --diff-filter=AM origin/main -- | grep -E '\.(cpp|hpp)$' | xargs clang-format --dry-run --Werror
