name: Clang Format Check

# Pull Request を main ブランチに対して行った場合に実行
on:
  pull_request:
    branches:
      - main

jobs:
  clang-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up clang-format
        run: |
          sudo apt-get install clang-format

      - name: Check code formatting
        run: |
          git fetch origin main
          # .cpp と .hpp ファイルだけを対象にフォーマットチェック
          git diff --name-only --diff-filter=AM origin/main -- '*.cpp' '*.hpp' | xargs -r clang-format --dry-run --Werror