version: '3.8'
services:
  cpp-env:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # ホスト:コンテナ
    volumes:
      - ../../:/usr/src/app  # プロジェクト全体をコンテナにマウント
    tty: true
networks:
  default:
    name: webserv_test_default

